# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 토스트 굽는 개발자
email: redism@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  토스트 굽는 개발자 설명
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://redism.github.io" # the base hostname & protocol for your site
twitter_username: redism
github_username:  redism

# Build settings
name: Jeff Oh
markdown: kramdown
